name: Deploy Firebase Function
on:
  push:
    branches:
      - main
jobs:
  deploy_staging:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Install dependencies
        run: npm install
      - name: Deploy Firebase function to staging
        run: |
          npx firebase use ${{ secrets.PROJECT_ID }} --token ${{ secrets.FIREBASE_TOKEN }}
          npx firebase deploy --only functions --token ${{ secrets.FIREBASE_TOKEN }}
  deploy_production:
    needs: deploy_staging
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Install dependencies
        run: npm install
      - name: Deploy Firebase function to production
        run: |
          npx firebase use ${{ secrets.PROJECT_ID }} --token ${{ secrets.FIREBASE_TOKEN }}
          npx firebase deploy --only functions --token ${{ secrets.FIREBASE_TOKEN }}
