name: Deploy to environments

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      ENVIRONMENT:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        options: ['staging', 'production']

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ env.ENVIRONMENT }}
      url: https://${{ env.ENVIRONMENT }}.example.com
    steps:
      - name: Deploy to ${{ env.ENVIRONMENT }}
        env:
          SECRET_NAME: ${{ secrets[env.ENVIRONMENT + '_SECRET'] }}
        run: |
          echo "Deploying to ${{ env.ENVIRONMENT }} environment with secret $SECRET_NAME"

  release:
    needs: deploy
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://example.com
    steps:
      - name: Deploy to production
        env:
          SECRET_NAME: ${{ secrets.PRODUCTION_SECRET }}
        run: |
          echo "Deploying to production environment with secret $SECRET_NAME"
