name: Deploy to environments

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://staging.example.com
    steps:
      - name: Deploy to staging
        env:
          SECRET_NAME: ${{ secrets.STAGING_SECRET }}
        run: echo "Deploying to staging environment with secret $SECRET_NAME"
  release:
    needs: deploy
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://example.com
    steps:
      - name: Deploy to production
        env:
          SECRET_NAME: ${{ secrets.PRODUCTION_SECRET }}
        run: echo "Deploying to production environment with secret $SECRET_NAME"
