name: Deploy to environments

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        options: ['staging', 'production']

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set environment variables
        run: |
          if [ ${{ github.event_name }} == 'workflow_dispatch' ]; then
            read -p 'Deploy to which environment? (staging/production): ' ENVIRONMENT
            export ENVIRONMENT
          else
            export ENVIRONMENT=staging
          fi

          export SECRET_NAME=${{ secrets.${ENVIRONMENT^^}_SECRET }}
          echo "::debug::SECRET_NAME=$SECRET_NAME"

      - name: Deploy to ${{ env.ENVIRONMENT }} environment
        run: echo "Deploying to ${{ env.ENVIRONMENT }} environment with secret $SECRET_NAME"
